mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/ggkt/vod/mapper/xml/*.xml

server:
  port: 8301

spring:
  application:
    name: service-vod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/classroom_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

tencent:
  cos:
    file:
      bucketname: atguigu-1305756827
      region: ap-nanjing
      secretid: AKIDPpAOXlzAZzSybBfDrXAb4dDgCoNycCh0
      secretkey: EJJLm8Y7n1JgBvVyV3Nd1OduMj1GQceZ